name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        name: install pnpm
        id: pnpm-install
        with:
          version: 8.6.3

      - name: npm install
        run: |
          pnpm install

      - name: pnpm test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm run package
          pnpm run lint
          pnpm exec tsc
          pnpm test
